name = "aee-autonomous-engineering"
compatibility_date = "2026-04-14"

[site]
bucket = "./dist"

[build]
command = "rm -rf node_modules && rm -f package-lock.json && npm install && npm run build"
cwd = "."

[builds]
files = "dist"